//dummy data for job listing

export const jobData = [
  {
    id: 1,
    role: "App Developer",
    type: "fullTime",
    team: "Engineering",
    city: "New York",
  },
  {
    id: 2,
    role: "Bussiness Development",
    type: "fullTime",
    team: "Bussiness",
    city: "Chicago",
  },
  {
    id: 3,
    role: "Manager",
    type: "fullTime",
    team: "Finance",
    city: "California",
  },
  {
    id: 4,
    role: "Sales Executive",
    type: "partTime",
    team: "Bussiness",
    city: "Texas",
  },
  {
    id: 5,
    role: "Desiner",
    type: "partTime",
    team: "Design",
    city: "Queens",
  },
  {
    id: 25,
    role: "UI Developer",
    type: "partTime",
    team: "Design",
    city: "Berlyn",
  },
  {
    id: 6,
    role: "Bussiness Executive",
    type: "fullTime",
    team: "Bussiness",
    city: "Los Angeles",
  },
  {
    id: 7,
    role: "Finance Associate",
    type: "partTime",
    team: "Finance",
    city: "Washington DC",
  },
  {
    id: 8,
    role: "Junior Developer",
    type: "internship",
    team: "Engineering",
    city: "Salt Lake",
  },
  {
    id: 10,
    role: "Associate Executive",
    type: "partTime",
    team: "Finance",
    city: "Abu Dabi",
  },
  {
    id: 9,
    role: "Finance Analyst",
    type: "internship",
    team: "Finance",
    city: "Saudi",
  },
  {
    id: 11,
    role: "Senior Engineer",
    type: "fullTime",
    team: "Engineering",
    city: "London",
  },
  {
    id: 21,
    role: "Web Developer",
    type: "fullTime",
    team: "Engineering",
    city: "West Virginia",
  },
  {
    id: 12,
    role: "Senior Bussiness Development",
    type: "fullTime",
    team: "Bussiness",
    city: "Canada",
  },
  {
    id: 13,
    role: "General Manager",
    type: "fullTime",
    team: "Finance",
    city: "India",
  },
  {
    id: 14,
    role: "Inbound Sales Executive",
    type: "partTime",
    team: "Bussiness",
    city: "Moscow",
  },
  {
    id: 15,
    role: "Interior Desiner",
    type: "partTime",
    team: "Design",
    city: "Beijing",
  },
  {
    id: 35,
    role: "UI Developer",
    type: "partTime",
    team: "Design",
    city: "Tokyo",
  },
  {
    id: 16,
    role: "Senior Bussiness Executive",
    type: "fullTime",
    team: "Bussiness",
    city: "Singapore",
  },
  {
    id: 17,
    role: "Virtual Finance Associate",
    type: "partTime",
    team: "Finance",
    city: "Sydney",
  },
  {
    id: 18,
    role: "Junior App Developer",
    type: "internship",
    team: "Engineering",
    city: "Paris",
  },
  {
    id: 30,
    role: "Associate Customer Executive",
    type: "partTime",
    team: "Finance",
    city: "New york",
  },
  {
    id: 19,
    role: "Finance Report Analyst",
    type: "internship",
    team: "Finance",
    city: "Boston",
  },
  {
    id: 211,
    role: "Senior Civil Engineer",
    type: "fullTime",
    team: "Engineering",
    city: "Gotham City",
  },
];
